name: Setup OpenTofu
description: Install and cache OpenTofu
inputs:
  working-directory:
    description: Directory containing TF code
    required: true
  tofu-version-file:
    description: Path to .tofu-version file relative to working-directory
    required: false
    default: .tofu-version
  install-tf-summarize:
    description: Install tf-summarize for plan summaries
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version_file: ${{ inputs.working-directory }}/${{ inputs.tofu-version-file }}

    - shell: bash
      run: |
        cache_dir="$HOME/.terraform.d/plugin-cache"
        mkdir -p "$cache_dir"
        echo "TF_PLUGIN_CACHE_DIR=$cache_dir" >> "$GITHUB_ENV"

    - uses: actions/cache@v5
      with:
        path: ~/.terraform.d/plugin-cache
        key: tofu-providers-${{ runner.os }}-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-directory)) }}

    - uses: kishaningithub/setup-tf-summarize@v2
      if: ${{ inputs.install-tf-summarize == 'true' }}
